### PR TITLE
Add simple benchmark for OpenStreetMap polygons

### PR DESCRIPTION
**Pull request by bcamper**
Re: issue #4, this is a simple benchmark for OpenStreetMap polygons, based on the libtess.js triangulation example (could certainly be improved if integrated into the newer test framework you've setup). This was the easiest way to get it up and running, feel free to take or change whichever pieces you want!

Polygons are sourced from [Mapzen's Vector Tile Service](http://mapzen.com/vector), which serves OSM polygons commonly used for rendering (buildings, land & water areas, etc.). This does benchmarks for 4 sets of polygons, one for each zoom level from 14 to 17, all centered on the same lat-lng in Midtown Manhattan. For each zoom level, polygons are simplified to a precision of 1 pixel (assuming a device pixel density of 1). Higher zoom levels have fewer polygons with more vertices each, lower zoom levels have more polygons with fewer vertices each. The benchmark is set to tessellate each polygon set 10 times.

Other notes affecting performance:
- Each vertex is stored as a separate JS array, [x, y]. In the other examples, it looks like vertices have been flattened into one array. But for rendering in [Tangram](http://github.com/tangrams/tangram), we receive geometries as GeoJSON; we could flatten the array before tessellation (and should if this is more performant!), though then we would probably also want to incorporate that time into the benchmark (to reflect how this source data can be used in real-world applications anyway). We could also serve data in a flattened list, but for now wanted this benchmark to reflect the lower common denominator of using GeoJSON source data.
- After tessellation, final vertices are converted to a `Float32Array`. This also isn't strictly a tessellation step, but again reflects real-world use for WebGL.

Questions/ideas, let me know.

### CODE REVIEW

**Comment by brendankenny** [comment]
hey, this is great! In general I definitely agree that benchmarks should reflect reality. It helps to keep optimizations in perspective and modern JS JITs are so complicated that something like converting from GeoJSON or to a Float32Array could have performance consequences we won't see without testing it, through everything from parse time to inlining decisions to register pressure.

First things first, would you mind signing the Google [Contributor License Agreement](https://developers.google.com/open-source/cla/individual) so that I can incorporate your PR? I don't see one under your name right now.

**Comment by bcamper** [comment]
Sure thing, added the CLA. Also fixed some lint (having a problem running the tests locally, but looks fine now).

Another point on this data: the original geometry was in lat-lng, and before adding here has been projected into spherical mercator, then linearly scaled to a local coordinate system of the tile the poly belongs to. Shouldn't affect performance AFAIK, but a note that if you were to plot these polys as-is, they would not appear positioned correctly. (Can update this data if that's desired.)

**Comment by brendankenny** [comment]
LGTM! We can look at integrating into the existing tests later.

**Comment by brendankenny** [comment]
two things:
1. I added some license info to the top of the example files. See [nyc_midtown_17.js](https://github.com/brendankenny/libtess.js/blob/gh-pages/examples/osm/nyc_midtown_17.js), for instance. Let me know if that doesn't work and we can make it better.
2. Not sure if this is the same linting problem you mentioned, but I found jshint + jscs took 2 minutes to run over just those example files, so I removed them from the lint task since we've checked them once and they're unlikely to change much now :)

**Comment by bcamper** [comment]
Thanks, license works for me.

**Pull request merged**
